"""initial_schema

Revision ID: 18feaeb4a6c9
Revises: 
Create Date: 2026-06-10 19:10:41.949319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18feaeb4a6c9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('monthly_allocation_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('monthly_allocation_ngn', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('annual_allocation_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('approved_mtd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('paid_mtd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('approved_ytd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('deferred_approved', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department', 'month', 'year', name='uq_budget_dept_month_year')
    )
    op.create_index(op.f('ix_category_budgets_department'), 'category_budgets', ['department'], unique=False)
    op.create_index(op.f('ix_category_budgets_id'), 'category_budgets', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('alternate_email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('rate_to_usd', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('month_name', sa.String(length=10), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cost_type', sa.String(length=10), nullable=False),
    sa.Column('supporting_justification', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('urgency_reason', sa.Text(), nullable=True),
    sa.Column('urgency_category', sa.String(length=100), nullable=True),
    sa.Column('requested_payment_date', sa.Date(), nullable=True),
    sa.Column('finance_authoriser', sa.String(length=255), nullable=True),
    sa.Column('budget_over_limit_flag', sa.Boolean(), nullable=False),
    sa.Column('hod_decision', sa.String(length=20), nullable=True),
    sa.Column('hod_comment', sa.Text(), nullable=True),
    sa.Column('hod_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hod_decided_by', sa.Integer(), nullable=True),
    sa.Column('finance_qc_status', sa.String(length=20), nullable=True),
    sa.Column('finance_qc_comment', sa.Text(), nullable=True),
    sa.Column('finance_qc_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finance_qc_by', sa.Integer(), nullable=True),
    sa.Column('cfo_decision', sa.String(length=30), nullable=True),
    sa.Column('cfo_approved_amount', sa.String(length=20), nullable=True),
    sa.Column('cfo_reason', sa.Text(), nullable=True),
    sa.Column('cfo_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cfo_decided_by', sa.Integer(), nullable=True),
    sa.Column('cfo_post_deferral', sa.Boolean(), nullable=False),
    sa.Column('cfo_post_deferral_reason', sa.Text(), nullable=True),
    sa.Column('cfo_post_defer_to_month', sa.Integer(), nullable=True),
    sa.Column('ceo_decision', sa.String(length=20), nullable=True),
    sa.Column('ceo_reason', sa.Text(), nullable=True),
    sa.Column('ceo_decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ceo_decided_by', sa.Integer(), nullable=True),
    sa.Column('treasury_payment_status', sa.String(length=30), nullable=True),
    sa.Column('treasury_comment', sa.Text(), nullable=True),
    sa.Column('treasury_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('treasury_updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ceo_decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cfo_decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finance_qc_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hod_decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['treasury_updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_department'), 'submissions', ['department'], unique=False)
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_submission_id'), 'submissions', ['submission_id'], unique=True)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('amount_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_submission_id'), 'audit_log', ['submission_id'], unique=False)
    op.create_table('line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('vendor_name', sa.String(length=255), nullable=False),
    sa.Column('invoice_no', sa.String(length=100), nullable=False),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('items_products', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('billing_period_start', sa.Date(), nullable=False),
    sa.Column('billing_period_end', sa.Date(), nullable=False),
    sa.Column('payment_tracking_code', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('status_remarks', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('equivalent_usd', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('exchange_rate_used', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('approved_usd', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('is_arrear', sa.Boolean(), nullable=False),
    sa.Column('arrear_type', sa.String(length=50), nullable=True),
    sa.Column('cfo_deferred', sa.Boolean(), nullable=False),
    sa.Column('cfo_defer_to_month', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_line_items_id'), 'line_items', ['id'], unique=False)
    op.create_index(op.f('ix_line_items_submission_id'), 'line_items', ['submission_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_line_items_submission_id'), table_name='line_items')
    op.drop_index(op.f('ix_line_items_id'), table_name='line_items')
    op.drop_table('line_items')
    op.drop_index(op.f('ix_audit_log_submission_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_submissions_submission_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_department'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_table('exchange_rates')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_category_budgets_id'), table_name='category_budgets')
    op.drop_index(op.f('ix_category_budgets_department'), table_name='category_budgets')
    op.drop_table('category_budgets')
    # ### end Alembic commands ###
